_format_version: "3.0"
consumers:
- keyauth_credentials:
  - key: dfreese-key
  tags:
  - sales
  - customer
  username: dfreese
- keyauth_credentials:
  - key: jdoe-key
  tags:
  - sales
  - customer
  username: jdoe
- keyauth_credentials:
  - key: jsmith-key
  tags:
  - sales
  - customer
  username: jsmith
plugins:
- config:
    key_names:
    - apikey
  name: key-auth
  service: customer-information-service
- config:
    cache_ttl: 300
    content_type:
    - text/plain
    - application/json
    redis:
      cluster_addresses: null
      sentinel_addresses: null
    request_method:
    - GET
    - HEAD
    response_code:
    - 200
    strategy: memory
  name: proxy-cache-advanced
  route: customer-information-service_get-cust-info
- config:
    add:
      body: []
      headers:
      - 'X-MyHeader: Konnect!'
  enabled: true
  name: response-transformer
services:
- host: host.docker.internal
  id: 690e812e-2873-566a-b02f-d03e0bf8ff69
  name: customer-information-service
  path: /
  plugins:
  - config:
      access:
      - "local ns='/customers' -- this strips the '/customers' namespace from the
        path\nlocal nst=ns:sub(-1,-1)=='/' and ns or (ns..'/')\nlocal function sn(u)\n\tlocal
        s,e=u:find(nst,1,true)\n\tif s then\n\t\treturn u:sub(1,s)..u:sub(e+1,-1)\n\tend\n\tif
        u:sub(-#ns,-1)==ns then\n\t\tu=u:sub(1,-#ns-1)\n\t\tif u=='' then u='/' end\n\tend\n\treturn
        u\nend\nngx.var.upstream_uri=sn(ngx.var.upstream_uri)"
    name: pre-function
  port: 5051
  protocol: http
  routes:
  - id: 5984bb2d-328e-5785-a06a-f639c3a59d94
    methods:
    - GET
    name: customer-information-service_get-cust-info
    paths:
    - ~/customers/customer$
    plugins: []
    regex_priority: 200
    strip_path: false
    tags:
    - sales
    - customer
  - id: 37cbdca9-74d9-51ec-ab8b-008d96f9bd75
    methods:
    - GET
    name: customer-information-service_health_get
    paths:
    - ~/customers/health$
    plugins: []
    regex_priority: 200
    strip_path: false
    tags:
    - sales
    - customer
  tags:
  - sales
  - customer
upstreams: []
