_format_version: "3.0"
services:
- host: host.docker.internal
  id: 0cef4d36-9c39-5ac2-9d9f-190d8ea8a252
  name: flights-service
  path: /
  plugins:
  - config:
      access:
      - "local ns='/flights' -- this strips the '/flights' namespace from the path\nlocal
        nst=ns:sub(-1,-1)=='/' and ns or (ns..'/')\nlocal function sn(u)\n\tlocal
        s,e=u:find(nst,1,true)\n\tif s then\n\t\treturn u:sub(1,s)..u:sub(e+1,-1)\n\tend\n\tif
        u:sub(-#ns,-1)==ns then\n\t\tu=u:sub(1,-#ns-1)\n\t\tif u=='' then u='/' end\n\tend\n\treturn
        u\nend\nngx.var.upstream_uri=sn(ngx.var.upstream_uri)"
    name: pre-function
  - config:
      add:
        headers:
        - x-flights-api:v1
    name: response-transformer
  port: 5052
  protocol: http
  routes:
  - id: 7b2dbd94-ec5b-5ae8-b6d5-4c8b16ce0b06
    methods:
    - GET
    name: flights-service_get-flights
    paths:
    - ~/flights/flights$
    plugins: []
    regex_priority: 200
    strip_path: false
    tags:
    - flight-data
    - flights
  - id: 3210c3ed-9976-500d-ac03-07eaac972ad0
    methods:
    - GET
    name: flights-service_get-flight-by-number
    paths:
    - ~/flights/flights/(?<flightnumber>[^#?/]+)$
    plugins: []
    regex_priority: 100
    strip_path: false
    tags:
    - flight-data
    - flights
  - id: 08020aa2-6106-59ec-903a-3459e7cbb629
    methods:
    - GET
    name: flights-service_get-flight-details
    paths:
    - ~/flights/flights/(?<flightnumber>[^#?/]+)/details$
    plugins: []
    regex_priority: 100
    strip_path: false
    tags:
    - flight-data
    - flights
  - id: a5023323-0468-5a77-baf2-13578fec61b0
    methods:
    - GET
    name: flights-service_health_get
    paths:
    - ~/flights/health$
    plugins: []
    regex_priority: 200
    strip_path: false
    tags:
    - flight-data
    - flights
  tags:
  - flight-data
  - flights
upstreams: []
