name: Build Flights API - Generate Kong Configs

on:
  workflow_dispatch:
  # Run if someone pushes to the feature branch (during development)
  push:
    branches:
      - main
    paths:
      - "flight-data/flights/opeanapi.yaml"
      - "flight-data/flights/kong/**"
      - ".github/workflows/build-flights.yaml"

jobs:
  oas-to-kong:
    name: Convert OAS to Kong configurations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup deck
        uses: kong/setup-deck@v1
        with:
          deck-version: "1.40.3"
          wrapper: false

      - name: Install Insomnia
        run: |
          curl -sL https://github.com/Kong/insomnia/releases/download/lib%408.6.1/inso-linux-8.6.1.tar.xz -o inso.tar.xz
          sudo tar -xf inso.tar.xz -C /tmp/
          cp /tmp/inso /usr/local/bin/

      - name: Lint blog spec
        run: inso lint spec flight-data/flights/opeanapi.yaml

      - name: Generate Kong Declarative Configs from Spec
        run: |
          deck file openapi2kong --spec flight-data/flights/openapi.yaml \
          --output-file flight-data/flights/kong/.generated/kong.yaml

      - name: Add path-based routing namespace
        run: |
          deck file namespace -s  flight-data/flights/kong/.generated/kong.yaml -o  flight-data/flights/kong/.generated/kong.yaml --path-prefix=/flights

      - name: Add plugin configuration
        run: |
          deck file merge flight-data/flights/kong/.generated/kong.yaml \
          flight-data/flights/kong/plugins/*.yaml \
          --output-file flight-data/flights/kong/.generated/kong.yaml

      - name: Add consumer configuration
        run: |
          deck file merge flight-data/flights/kong/.generated/kong.yaml \
          flight-data/flights/kong/consumers/*.yaml \
          --output-file flight-data/flights/kong/.generated/kong.yaml

      - name: Add tags
        run: |
          cat flight-data/flights/kong/.generated/kong.yaml | \
          deck file add-tags flight-data flights \
          --selector "$.services[*]" \
          --selector "$.services[*].routes[*]"  \
          --selector "$.consumers[*]" \
          --output-file flight-data/flights/kong/.generated/kong.yaml

      - name: Add environment Specific Patch
        run: |
          cat flight-data/flights/kong/.generated/kong.yaml | \
          deck file patch flight-data/flights/kong/patches.yaml \
          --output-file flight-data/flights/kong/.generated/kong.yaml

      - name: Validate decK state file locally
        run: |
          deck file validate flight-data/flights/kong/.generated/kong.yaml

      - name: Copy to artifact directory
        run: |
          cp flight-data/flights/kong/.generated/kong.yaml \
             .github/artifacts/flights/flights-kong.yaml

      - name: Validate connectivity to Konnect
        run: |
          deck gateway ping \
          --konnect-control-plane-name ${{vars.KONNECT_INTERNAL_CP}} \
          --konnect-token ${{ secrets.KONNECT_PAT }} \
          --konnect-addr ${{vars.KONNECT_ADDR}}

      - name: deck diff
        id: deck-diff
        # deck diff results in a multi-line output, which requires some
        #  bash gymnastics to handle and pass through to the next job.
        #  See: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-of-a-multiline-string
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "DIFF<<$EOF" >> $GITHUB_ENV
          deck gateway diff --select-tag flight-data --select-tag flights \
          .github/artifacts/flights/flights-kong.yaml \
          --konnect-control-plane-name ${{vars.KONNECT_INTERNAL_CP}} \
          --konnect-token ${{ secrets.KONNECT_PAT }} \
          --konnect-addr ${{vars.KONNECT_ADDR}}>> $GITHUB_ENV
          echo "$EOF" >> $GITHUB_ENV

      #an artifact file will be committed only if it the Kong config differs from the previous one.
      - name: Check status of any files to be committed
        run: git status

      - name: Create PR to stage changes for the Kong Gateway in production
        uses: peter-evans/create-pull-request@v5
        with:
          title: "❗PRD❗: Staged changes for Kong Gateway PRD deployment - Flights API"
          labels: "PRD,kong,flights"
          body: "Merging this PR will result in the following changes deployed to PRD \n\n ```\n${{env.DIFF}}\n```"
          branch-suffix: random
